### PR TITLE
Initial template

### PR DESCRIPTION
**Pull request by elliotblanchard**

### CODE REVIEW

**Comment by codenamejason** [comment]
Create an initial-template branch for this and then other community members can have input as well.

**Comment by pabloruiz55** [comment]
@elliotblanchard I know I'm 3 months late, but I just started helping maintain the repo. Could you please elaborate a bit on what this PR brings to the table? Is your intention to propose changing what the initial template for a fresh Scaffold-eth install is?

**Comment by pabloruiz55** [comment]
@elliotblanchard I know I'm 3 months late, but I just started helping maintain the repo. Could you please elaborate a bit on what this PR brings to the table? Is your intention to propose changing what the initial template for a fresh Scaffold-eth install is?

**Comment by elliotblanchard** [comment]
Hi Pablo,

I hadn't actually meant to submit a PR so please ignore.

Sorry for any confusion,

Elliot

**Comment by pabloruiz55** [comment]
No worries!

**Pull request closed without merging**
