### PR TITLE
update to add in coinbase -- currently it is failing though since the…

### PR DESCRIPTION
**Pull request by tomafc330**
… signatures don't seem to match up

### CODE REVIEW

**Comment by tomafc330** [comment]
I am able to sign in with the coinbase wallet but the signature doesn't return the original account for some reason: 
image

**Comment by azf20** [comment]
hello! where is the signature code, would be keen to check this out

**Comment by tomafc330** [comment]
@azf20 Vote.js:16

**Comment by codenamejason** [comment]
@azf20 can we merge this one?

**Comment by azf20** [comment]
Agreed. It also seems like Coinbase wallet's preferred approach has changed in any case: https://blog.coinbase.com/coinbase-wallet-introduces-new-browser-extension-dd067403b86

**Comment by pabloruiz55** [comment]
Closing in favor of issue https://github.com/austintgriffith/scaffold-eth/issues/225, waiting for someone to pick it up and add the Coinbase Wallet integration.

**Pull request closed without merging**
