### PR TITLE
Sanity checks for when connection is offline

### PR DESCRIPTION
**Pull request by pabloruiz55**
A stab at solving #198.

With these fixes, if you are offline and you still want to code while on localhost + local chain, you should not get any errors from the components that are looking for stuff on mainnet.

It doesn't solve the issue when you go to Chrome's console -> network -> simulate offline, 
BUT it does work fine when you are truly offline or in airplane mode.

### CODE REVIEW

**Review by azf20 — CHANGES_REQUESTED** [review]
Nice! Works great offline but when I went online it wasn't connecting - not sure if it's a browser specific thing, but I think `navigator.onLine` is a boolean rather than a string when I print it out?
`navigator.onLine: false`
I think `navigator.onLine === 'online'` can be replaced by just checking for `navigator.onLine`?

**Comment by pabloruiz55** [comment]
> Nice! Works great offline but when I went online it wasn't connecting - not sure if it's a browser specific thing, but I think `navigator.onLine` is a boolean rather than a string when I print it out?
> `navigator.onLine: false`
> I think `navigator.onLine === 'online'` can be replaced by just checking for `navigator.onLine`?

You are absolutely right. Not sure why I did that there and why I thought it was working fine, but it's fixed now. Thanks!

**Review by NhlanhlaHasane — APPROVED** [review]

**Comment by pabloruiz55** [comment]
@azf20 whenever you get a chance please review again and approve the changes so Github allows me to merge. Thanks!

**Review by azf20 — APPROVED** [review]
LGTM!

**Pull request merged**
