### PR TITLE
first template

### PR DESCRIPTION
**Pull request by DrHongos**
First template for rapid prototipation.
Used similar contract : TO MODIFY
Started with basic inputs: TO CHECK and link to contracts.

### CODE REVIEW

**Comment by pabloruiz55** [comment]
Hey @DrHongos  I know I'm 6 months late, but I just started helping maintain the repo. Could you please elaborate a bit on what this PR brings to the table? Is your intention to propose changing what the initial template for a fresh Scaffold-eth install is?

**Comment by codenamejason** [comment]
After looking at the YourContract.sol I don't think this should be merged at all, if anything a branch could be made but would need some context in the readme or something and explain how it is useful to others.

**Comment by DrHongos** [comment]
OMG, i dont remember this, probably an error on my behalf.. sorry for the inconvenience

**Comment by pabloruiz55** [comment]
No worrries!

**Pull request closed without merging**
