### PR TITLE
updated: subgraph explorer: uniswap, compound, synthetix, balancer etc

### PR DESCRIPTION
**Pull request by harryranakl**
subgraph explorer: uniswap, compound, synthetix, balancer, aave, dydx, kyber, curve and chainlink

### CODE REVIEW

**Comment by pabloruiz55** [comment]
Thanks for submitting this!
I'd avoid pushing it into master as we want to keep it as clean / simple as possible. Instead let's add it into a new branch that people can refer to. Could you add any necessary steps / instructions on how this is used, motivation, etc?
Thanks!

**Comment by harryranakl** [comment]
thnaks, let me update the readme

**Comment by harryranakl** [comment]
Screenshot 2021-06-29 at 10 51 37 AM

**Comment by pabloruiz55** [comment]
Nice! Are you finished with it? If yes I'll merge and add the tutorial to the docs.

**Comment by harryranakl** [comment]
> Nice! Are you finished with it? If yes I'll merge and add the tutorial to the docs.

yup, plz help to merge it.

**Pull request merged**
