### PR TITLE
turned off autocomplete on inputs

### PR DESCRIPTION
**Pull request by karbafoo**
added ` autoComplete="off"` for `<Input />` elements

### CODE REVIEW

**Review by codenamejason — DISMISSED** [review]
Looks good to me and seems he got all the spots.

**Comment by codenamejason** [comment]
yarn.lock should be ignored from commits @karbafoo

**Review by codenamejason — APPROVED** [review]

**Comment by codenamejason** [comment]
I can't get it to remove this conflict.... $%#@$

**Comment by karbafoo** [comment]
sorry about that

**Comment by codenamejason** [comment]
@karbafoo can we close this one and create a new pr, I can't seem to resolve the yarn.lock conflict...

**Comment by karbafoo** [comment]
ofc

**Pull request closed without merging**
